openapi: 3.0.0
info:
  title: API de Gestão de Eventos Esportivos
  description: API RESTful para a gestão de corridas e caminhadas esportivas, incluindo registro de atletas, cronometragem e classificação.
  version: "1.0"
servers:
  - url: https://lvwdj.wiremockapi.cloud/v1
    description: Mock
tags:
  - name: Configuração
    description: Conteúdo para configurar o front-end
  - name: Atletas
    description: Dados dos atletas que participarão do evento
  - name: Cronometragem
    description: Gestão do tempo da corrida de cada atleta
  - name: Classificação
    description: Classificação da corrida
paths:
  /configuracoes/hora_servidor:
    get:
      tags:
        - Configuração
      summary: Obtem a hora do servidor
      description: Retorna a hora atual do servidor no formato `HH:mm:ss`.
      responses:
        '200':
          description: Hora do servidor retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  hora:
                    type: string
                    description: Hora no formato HH:mm:ss
              example:
                hora: "14:35:22"
        '500':
          description: Erro ao obter a hora do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  codigo:
                    type: string
                    description: Código do erro
                  mensagem:
                    type: string
                    description: Mensagem do erro
              example:
                hora: "43434343"
                mensagem: "Ocorreu um erro no servidor"

  /atletas:
    get:
      tags:
        - Atletas
      summary: Listar atletas
      description: Retorna uma lista de todos os atletas cadastrados.
      responses:
        '200':
          description: Lista de atletas retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  atletas:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Identificação do atleta na base
                        nome:
                          type: string
                          description: Nome do atleta
                        documento:
                          type: string
                          description: Documento do atleta
                        numero_peito:
                          type: string
                          description: Número de peito associado ao atleta
                        sexo:
                          type: string
                          description: Sexo do atleta
                        data_nascimento:
                          type: string
                          format: date
                          description: Data de nascimento no formato dd/MM/yyyy
              example:
                atletas:
                  - id: "1"
                    nome: "João da Silva"
                    documento: "12345678900"
                    numero_peito: "101"
                    sexo: "Masculino"
                    data_nascimento: "01/01/1990"
                  - id: "2"
                    nome: "Maria Souza"
                    documento: "98765432100"
                    numero_peito: "102"
                    sexo: "Feminino"
                    data_nascimento: "15/03/1985"
    post:
      tags:
        - Atletas
      summary: Criar novo atleta
      description: Cadastra um novo atleta na base de dados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do atleta
                  example: "João da Silva"
                documento:
                  type: string
                  description: Documento do atleta
                  example: "12345678900"
                numero_peito:
                  type: string
                  description: Número de peito associado ao atleta
                  example: "101"
                sexo:
                  type: string
                  description: Sexo do atleta
                  example: "Masculino"
                data_nascimento:
                  type: string
                  format: date
                  description: Data de nascimento no formato dd/MM/yyyy
                  example: "01/01/1990"
                nome_operador:
                  type: string
                  description: Nome do operador que registrou o atleta
                  example: "Carlos"
      responses:
        '200':
          description: Atleta cadastrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Identificação do atleta na base
                  nome:
                    type: string
                    description: Nome do atleta
                  documento:
                    type: string
                    description: Documento do atleta
                  numero_peito:
                    type: string
                    description: Número de peito associado ao atleta
                  sexo:
                    type: string
                    description: Sexo do atleta
                  data_nascimento:
                    type: string
                    format: date
                    description: Data de nascimento no formato dd/MM/yyyy
                  nome_operador:
                    type: string
                    description: Nome do operador que registrou o atleta
              example:
                id: "1"
                nome: "João da Silva"
                documento: "12345678900"
                numero_peito: "101"
                sexo: "Masculino"
                data_nascimento: "01/01/1990"
                nome_operador: "Carlos"

  /atletas/{id_atleta}:
    put:
      tags:
        - Atletas
      summary: Atualizar dados de um atleta
      description: Atualiza as informações de um atleta cadastrado.
      parameters:
        - name: id_atleta
          in: path
          required: true
          description: ID do atleta
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do atleta
                documento:
                  type: string
                  description: Documento do atleta
                numero_peito:
                  type: string
                  description: Número de peito associado ao atleta
                sexo:
                  type: string
                  description: Sexo do atleta
                data_nascimento:
                  type: string
                  format: date
                  description: Data de nascimento no formato dd/MM/yyyy
                nome_operador:
                  type: string
                  description: Nome do operador que realizou a atualização
      responses:
        '200':
          description: Dados do atleta atualizados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Identificação do atleta na base
                  nome:
                    type: string
                    description: Nome do atleta
                  documento:
                    type: string
                    description: Documento do atleta
                  numero_peito:
                    type: string
                    description: Número de peito associado ao atleta
                  sexo:
                    type: string
                    description: Sexo do atleta
                  data_nascimento:
                    type: string
                    format: date
                    description: Data de nascimento no formato dd/MM/yyyy
                  nome_operador:
                    type: string
                    description: Nome do operador que realizou a atualização
              example:
                id: "1"
                nome: "João da Silva"
                documento: "12345678900"
                numero_peito: "101"
                sexo: "Masculino"
                data_nascimento: "01/01/1990"
                nome_operador: "Carlos"

  /cronometragem:
    post:
      tags:
        - Cronometragem
      summary: Registrar cronometragem de um atleta
      description: Registra o horário de início e término para o percurso de um atleta.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_atleta:
                  type: string
                  description: ID do atleta
                horario_inicio:
                  type: string
                  format: date-time
                  description: Horário de início
                horario_termino:
                  type: string
                  format: date-time
                  description: Horário de término
      responses:
        '200':
          description: Cronometragem registrada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_cronometragem:
                    type: string
                    description: ID da cronometragem registrada
              example:
                id_cronometragem: "202411200001"

  /classificacao:
    get:
      tags:
        - Classificação
      summary: Obter classificação
      description: Retorna a classificação dos atletas com base nos tempos registrados.
      responses:
        '200':
          description: Classificação retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  classificacao:
                    type: array
                    items:
                      type: object
                      properties:
                        posicao:
                          type: integer
                          description: Posição do atleta
                        id_atleta:
                          type: string
                          description: ID do atleta
                        tempo_total:
                          type: string
                          description: Tempo total no formato HH:mm:ss.SSS
              example:
                classificacao:
                  - posicao: 1
                    id_atleta: "1"
                    tempo_total: "00:25:30.125"
                  - posicao: 2
                    id_atleta: "2"
                    tempo_total: "00:27:15.300"
